# Generated by Django 5.1.2 on 2025-04-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
