# Generated by Django 5.1.2 on 2025-05-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
